spring.application.name=calorias

# CONFIGURAÇÃO BÁSICA DO SPRING
spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
spring.datasource.username=RM564007
spring.datasource.password=230896

# CONFIGURAÇÃO PARA O ORACLE DATABASE
# CRIAR A TABELA DE CONTROLE DE MIGRAÇÃO NO BANCO DE DADOS
spring.flyway.baselineOnMigrate=true

# MOSTRAR AS INSTRUÇÕES SQL EXECUTADAS NO BANCO DE DADOS
spring.jpa.show-sql=true

# QUEBRAR A EXIBIÇÃO DA INSTRUÇÃO SQL EM VÁRIAS LINHAS
spring.jpa.properties.hibernate.format_sql=true